In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
data=pd.read_csv('mnist-dataset/mnist_train.csv')

In [3]:
data.head()
data.shape

(60000, 785)

In [4]:
data.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [5]:
data=np.array(data)

In [6]:
m,n =data.shape

In [7]:
np.random.shuffle(data)

In [8]:
dev_data=data[0:1000].T

In [9]:
print(dev_data)

[[1 7 1 ... 2 5 8]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
dev_y=dev_data[0]

In [11]:
dev_x=dev_data[1:n]

In [12]:
dev_x=dev_x/255.

In [13]:
train_data=data[1000:m].T

In [14]:
print(train_data)

[[7 3 7 ... 7 4 8]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
train_y= train_data[0]

In [16]:
train_x=train_data[1:n]

In [17]:
train_x=train_x/255.

In [18]:
_,train_m =train_x.shape

In [19]:
train_data.shape

(785, 59000)

In [20]:
dev_x.shape

(784, 1000)

In [21]:
 train_y.shape

(59000,)

In [22]:
def init_params():
    W1 = np.random.randn(128, 784) * np.sqrt(2 / 784)
    b1 = np.zeros((128, 1))
    W2 = np.random.randn(10, 128) * np.sqrt(2 / 128)
    b2 = np.zeros((10, 1))
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)


def softmax(Z):
    expZ = np.exp(Z - np.max(Z, axis=0, keepdims=True))
    return expZ / np.sum(expZ, axis=0, keepdims=True)
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    db2 = 1 / m * np.sum(dZ2, axis=1, keepdims=True)
    db1 = 1 / m * np.sum(dZ1, axis=1, keepdims=True)
    dW1 = 1 / m * dZ1.dot(X.T)

    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [23]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [24]:
W1, b1, W2, b2 = gradient_descent(train_x, train_y, 0.10, 500)

Iteration:  0
[2 9 9 ... 9 9 7] [7 3 7 ... 7 4 8]
0.1294406779661017
Iteration:  10
[2 8 7 ... 7 4 1] [7 3 7 ... 7 4 8]
0.6810338983050848
Iteration:  20
[2 8 7 ... 7 4 1] [7 3 7 ... 7 4 8]
0.773135593220339
Iteration:  30
[2 8 7 ... 7 4 1] [7 3 7 ... 7 4 8]
0.809728813559322
Iteration:  40
[2 3 7 ... 7 4 1] [7 3 7 ... 7 4 8]
0.8310508474576271
Iteration:  50
[2 3 7 ... 7 4 1] [7 3 7 ... 7 4 8]
0.8457288135593221
Iteration:  60
[3 3 7 ... 7 4 1] [7 3 7 ... 7 4 8]
0.8559152542372881
Iteration:  70
[3 3 7 ... 7 4 1] [7 3 7 ... 7 4 8]
0.863864406779661
Iteration:  80
[3 3 7 ... 7 4 1] [7 3 7 ... 7 4 8]
0.8700169491525424
Iteration:  90
[3 3 7 ... 7 4 3] [7 3 7 ... 7 4 8]
0.8755762711864407
Iteration:  100
[3 3 7 ... 7 4 3] [7 3 7 ... 7 4 8]
0.8798305084745762
Iteration:  110
[7 3 7 ... 7 4 3] [7 3 7 ... 7 4 8]
0.8833389830508475
Iteration:  120
[7 3 7 ... 7 4 3] [7 3 7 ... 7 4 8]
0.8863389830508475
Iteration:  130
[7 3 7 ... 7 4 3] [7 3 7 ... 7 4 8]
0.8884406779661017
Iteration:  140
[7 3

In [25]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = train_x[:, index, None]
    prediction = make_predictions(train_x[:, index, None], W1, b1, W2, b2)
    label = train_y[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

In [26]:
test_prediction(90001, W1, b1, W2, b2)


IndexError: index 90001 is out of bounds for axis 1 with size 59000

In [ ]:
dev_predictions = make_predictions(dev_x, W1, b1, W2, b2)
get_accuracy(dev_predictions, dev_y)